config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'signup', 	to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  get 'create',   to: 'events#new'
  post '/' => 'events#my_events', as: 'my_events'
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :events
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@event = current_user.events.build if logged_in?
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div class="row">
    <div class='col-md-9'>
      <% if params[:type] == 'user' %>
        <%= render "events/calendar", user: current_user %>
      <% else %>
        <%= render "events/calendar", user: nil %>
      <% end %>
    </div>
    <aside class="col-md-2">
      <div class="user_info">
        <%= link_to "Create a new event", create_path, class: 'form-control link-back' %>
        <% if current_user.events.any? %>
          <h3>Events (<%= current_user.events.count %>)</h3>
          <ol class="events">
            <%= render current_user.events.all %>
          </ol>
        <% end %>

      </div>
    </aside>
  </div>
<% else %>
	<div class="center jumbotron">
	  <h1>Welcome to the Event Calendar</h1>

	  <h2>
	    This is the home page for the
	    <a href="#">Event Calendar</a>.
	  </h2>

	  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
<% end %>