config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'signup', 	to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  get 'create',   to: 'events#new'
  post '/' => 'events#my_events', as: 'my_events'
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :datetime, presence: true
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 25 }
  default_scope -> { order(:datetime) }

  def self.call_notifications
  	Event.all.each do |e|
  		if (e.datetime - (DateTime.now + 3.hours)) <= 1.hours and (e.datetime - (DateTime.now + 3.hours)) >= 1.minute
        unless User.find(e.user_id).chat_id.nil? or User.find(e.user_id).chat_id == ''
  		    message = "You're less than one hour away from your event.\n#{e.name}\n#{e.content}\n#{e.datetime.strftime('%H:%M')}\n"
  		    TelegramNotification.send_message(User.find(e.user_id).chat_id, message)
        end
		  end
    end
  end

  def self.clear
  	Event.all.each do |e|
  		if e.datetime < (DateTime.now + 3.hours)
  			if e.repeat == "Daily"
  				event = Event.new(name: e.name, content: e.content, datetime: e.datetime + 1.day, repeat: e.repeat)
  				event.save
				elsif e.repeat == "Weekly"
					event = Event.new(name: e.name, content: e.content, datetime: e.datetime + 1.week, repeat: e.repeat)
  				event.save
				elsif e.repeat == "Monthly"
					event = Event.new(name: e.name, content: e.content, datetime: e.datetime + 1.month, repeat: e.repeat)
  				event.save
				elsif e.repeat == "Yearly"
					event = Event.new(name: e.name, content: e.content, datetime: e.datetime + 1.year, repeat: e.repeat)
  				event.save
				end
  			e.destroy
			end
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

	def show
		@event = Event.find(params[:id])
  end

  def destroy
  	Event.find(params[:id]).destroy
    flash[:success] = "Event deleted"
    redirect_to root_url
  end

  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(event_params)
    unless current_user.chat_id.nil? or current_user.chat_id == ''
      message = "You created new event.\n#{@event.name}\n#{@event.content}\n#{@event.datetime.strftime('%d.%m.%y %H:%M')}\n"
      TelegramNotification.send_message(current_user.chat_id, message)
    end
    @event[:user_id] = current_user.id
    if @event.save
      flash[:success] = "Event created!"
      redirect_to @event
    else      
      flash[:success] = "#{@event[:user_id]}"
      redirect_to root_url
    end
  end
  
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    unless current_user.chat_id.nil? or current_user.chat_id == ''
      message = "You updated your event.\n#{@event.name}\n#{@event.content}\n#{@event.datetime.strftime('%d.%m.%y %H:%M')}\n"
      TelegramNotification.send_message(current_user.chat_id, message)
    end
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
      redirect_to @event
    else
      render 'edit'
    end
  end

  def my_events
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

    def event_params
      params.require(:event).permit(:name, :content, :datetime, :repeat)
    end

    def correct_user
      @event = current_user.events.find_by(id: params[:id])
      redirect_to root_url if @event.nil?
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_calendar.html.erb
<% if user == nil %>
	<%= link_to 'Show only my events', my_events_path(:type => 'user'), method: :post, remote: true, class: 'filter' %>
	<%= month_calendar do |date| %>
		<%= date.day %>
		<% Event.all.sort_by{|e| e.datetime.strftime('%H:%M')}.each do |e| %>
		  <% if ((e.datetime.to_date == date) or (e.repeat == 'Daily') or (e.datetime.wday == date.wday and e.repeat == 'Weekly') or (e.datetime.day == date.day and e.repeat == 'Monthly') or (e.datetime.day == date.day and e.datetime.month == date.month and e.repeat == 'Yearly')) and date >= DateTime.now.to_date %>
		  	<%= link_to "#{e.datetime.strftime("%H:%M")} #{e.name}", event_path(e) %>
	  	<% end %>
		<% end %>
	<% end %>
<% else %>
	<%= link_to 'Show all events', my_events_path(:type => 'all'), method: :post, remote: true, class: 'filter' %>
	<%= month_calendar do |date| %>
		<%= date.day %>
		<% user.events.all.sort_by{|e| e.datetime.strftime('%H:%M')}.each do |e| %>
		  <% if ((e.datetime.to_date == date) or (e.repeat == 'Daily') or (e.datetime.wday == date.wday and e.repeat == 'Weekly') or (e.datetime.day == date.day and e.repeat == 'Monthly') or (e.datetime.day == date.day and e.datetime.month == date.month and e.repeat == 'Yearly')) and date >= DateTime.now.to_date %>
		  	<%= link_to "#{e.datetime.strftime("%H:%M")} #{e.name}", event_path(e) %>
	  	<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/events/_event.html.erb
<li id="event-<%= event.id %>">
  <div class="name"><%= link_to event.name, event %></div>
  <div class="timestamp">
    <%= event.datetime.strftime("%d.%m.%Y %H:%M") %>
  </div>
  <% if event.content != '' %>
  	<div class="content"><%= event.content %></div>
	<% end %>
</li>

app/views/events/edit.html.erb
<% provide(:title, "Event") %>
<h1>Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for @event  do |f|%>

      <%= f.input :name, input_html: { class: 'form-control' } %>

      <%= f.input :content, input_html: { class: 'form-control' } %>

      <%= f.input :datetime, as: :string, input_html: { class: 'form-control datetimepicker' }%>

      <%= f.label :repeat, "Frequency" %>
      <%= f.select(:repeat, ['Once','Daily','Weekly','Monthly','Yearly'], {} , { class: 'form-control' }) %>

      <%= f.submit "Edit this event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $('.datetimepicker').datetimepicker({ format: 'YYYY-MM-DD HH:mm' });
  });
</script>

app/views/events/my_events.js.erb
$('.col-md-9 *').remove();
<% if params[:type] == 'user' %>
	$('.col-md-9').append('<%= j render "events/calendar", user: current_user %>');
<% else %>
	$('.col-md-9').append('<%= j render "events/calendar", user: nil %>');
<% end %>

app/views/events/new.html.erb
<% provide(:title, "Event") %>
<h1>Event</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for @event  do |f|%>

      <%= f.input :name, input_html: { class: 'form-control' } %>

      <%= f.input :content, input_html: { class: 'form-control' } %>

      <%= f.input :datetime, as: :string, input_html: { class: 'form-control datetimepicker' }%>

      <%= f.label :repeat, "Frequency" %>
      <%= f.select(:repeat, ['Once','Daily','Weekly','Monthly','Yearly'], {} , { class: 'form-control' }) %>

      <%= f.submit "Create my event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $('.datetimepicker').datetimepicker({ format: 'YYYY-MM-DD HH:mm' });
  });
</script>

app/views/events/show.html.erb
<% provide(:title, "Event") %>
<h1>Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for @event  do |f|%>

      <%= f.input :name, input_html: { class: 'form-control', readonly: :readonly } %>

      <%= f.input :content, input_html: { class: 'form-control', readonly: :readonly } %>

      <%= f.input :datetime, as: :string, input_html: { class: 'form-control datetimepicker', disabled: :disabled }%>

      <%= f.label :repeat, "Frequency" %>
      <%= f.select(:repeat, [f.object.repeat], {} , { class: 'form-control', disabled: :disabled }) %>

      <div class='flex-row'>

        <% if current_user.id == @event.user_id %>

          <%= link_to "Delete", @event, method: :delete, class: 'form-control link-back', data: { confirm: "You sure?" } %>

          <%= link_to "Edit event", edit_event_path(@event), class: 'form-control link-back' %>

       <% end %>

      <%= link_to "Back to profile", current_user, class: 'form-control link-back' %>
     </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $('.datetimepicker').datetimepicker({ format: 'YYYY-MM-DD HH:mm' });
  });
</script>