config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'signup', 	to: 'users#new'
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  get 'create',   to: 'events#new'
  post '/' => 'events#my_events', as: 'my_events'
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :events
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "event calendar", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Home",     root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
              <%= link_to "Log Out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if yield(:title).empty? %>
      <title>Event Calendar</title>
    <% else %>
      <title><%= yield(:title) %> | Event Calendar</title>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>